<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Exam Marks Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background: #fff;
            color: #000;
        }

        .wrapper {
            width: 100%;
            max-width: 750px;
            margin: 0 auto;
        }

        .container {
            padding: 20px;
        }

        h2 {
            text-align: center;
            text-transform: uppercase;
            font-size: 18px;
            margin-bottom: 30px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 13px;
            margin-bottom: 30px;
        }

        th, td {
            border: 1px solid #999;
            padding: 8px;
            text-align: left;
        }

        th.theading {
            background-color: #e2e8f0;
            text-transform: uppercase;
            font-size: 12px;
            text-align: center;
        }

        tr:nth-child(even) td {
            background-color: #f9f9f9;
        }

        .footer {
            position: fixed;
            bottom: 15mm;
            left: 0;
            right: 0;
            text-align: center;
            font-style: italic;
            font-size: 12px;
            color: #555;
        }
    </style>
</head>
<body>
    <div class="wrapper">
        <div class="container">

            <div style="text-align: center; margin-bottom: 15px;">
                <img src="{{ public_path('images/logo.png') }}" alt="App Logo" style="max-height: 80px;">
            </div>

            <h2>Exam Marks Report - {{ $course->name }}</h2>

            <table>
                <thead>
                    <tr>
                        <th class="theading">#</th>
                        <th class="theading">Student Name</th>
                        <th class="theading">Matricule</th>
                        <th class="theading">Level</th>
                        <th class="theading">Mark / 70</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($examMarks as $index => $mark)
                        <tr>
                            <td>{{ $index + 1 }}</td>
                            <td>{{ $mark->student->user->name ?? 'N/A' }}</td>
                            <td>{{ $mark->student->matricule ?? 'N/A' }}</td>
                            <td>{{ $mark->student->level->name ?? 'N/A' }}</td>
                            <td>{{ $mark->mark }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

        </div>
    </div>

    <div class="footer">
        Generated by {{ config('app.name') }} on {{ now()->setTimezone($timezone)->format('Y-m-d') }} at {{ now()->setTimezone($timezone)->format('H:i a') }}
    </div>
</body>
</html>
